
DROP TABLE DETALLE_RESERVA_HABITACION;
DROP TABLE DETALLE_RESERVA_SERVICIO;
DROP TABLE RESERVA;
DROP TABLE CLIENTE;
DROP TABLE HABITACION;
DROP TABLE EMPLEADO;
DROP TABLE TIPOHABITACION;
DROP TABLE SERVICIO;
DROP TABLE USUARIO;



