-- Generado por Oracle SQL Developer Data Modeler 4.0.3.853
--   en:        2016-10-30 12:44:17 COT
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g

CREATE TABLE USUARIO
  (
    IDUSU         NUMBER NOT NULL ,
    USUARIO       VARCHAR2 (50 CHAR) NOT NULL ,
    PASSWORD      VARCHAR2 (100 CHAR) NOT NULL ,
    NOMBRE        VARCHAR2 (50 CHAR) ,
    APELLIDOPAT   VARCHAR2 (30 CHAR) ,
    APELLIDOMAT   VARCHAR2 (30 CHAR) ,
    EMAIL         VARCHAR2 (100 CHAR) NOT NULL ,
    ESTADO        VARCHAR2 (1 CHAR) DEFAULT '1' ,
    TIPO          VARCHAR2 (10 CHAR),
    FECHACREACION DATE DEFAULT SYSDATE
  ) ;
CREATE UNIQUE INDEX PK_USUARIO ON USUARIO
  (
    IDUSU ASC
  )
  ;
  ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY ( IDUSU ) ;
  ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_UN UNIQUE ( USUARIO , EMAIL ) ;
CREATE SEQUENCE SQ_USUARIO START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TG_USUARIO BEFORE
  INSERT ON USUARIO FOR EACH ROW WHEN (NEW.IDUSU IS NULL) BEGIN :NEW.IDUSU := SQ_USUARIO.NEXTVAL;
END;
/

CREATE TABLE TIPOHABITACION
  (
    IDTIPOHAB NUMBER NOT NULL ,
    NOMBRE    VARCHAR2 (50 CHAR) ,
    PRECIO    NUMBER
  ) ;
CREATE UNIQUE INDEX PK_TIPOHABITACION ON TIPOHABITACION
  (
    IDTIPOHAB ASC
  )
  ;
  ALTER TABLE TIPOHABITACION ADD CONSTRAINT PK_TIPOHABITACION PRIMARY KEY ( IDTIPOHAB ) ;
  ALTER TABLE TIPOHABITACION ADD CONSTRAINT TIPOHABITACION_UN UNIQUE ( NOMBRE ) ;
CREATE SEQUENCE SQ_TIPOHABITACION START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TG_TIPOHABITACION BEFORE
  INSERT ON TIPOHABITACION FOR EACH ROW WHEN (NEW.IDTIPOHAB IS NULL) BEGIN :NEW.IDTIPOHAB := SQ_TIPOHABITACION.NEXTVAL;
END;
/

CREATE TABLE SERVICIO
  (
    IDSERVICIO  NUMBER NOT NULL ,
    NOMBRE      VARCHAR2 (30 CHAR) NOT NULL ,
    DESCRIPCION VARCHAR2 (100 CHAR) ,
    PRECIO      NUMBER
  ) ;
CREATE UNIQUE INDEX PK_SERVICIO ON SERVICIO
  (
    IDSERVICIO ASC
  )
  ;
  ALTER TABLE SERVICIO ADD CONSTRAINT PK_SERVICIO PRIMARY KEY ( IDSERVICIO ) ;
  ALTER TABLE SERVICIO ADD CONSTRAINT SERVICIO_UN UNIQUE ( NOMBRE ) ;
CREATE SEQUENCE SQ_SERVICIO START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TG_SERVICIO BEFORE
  INSERT ON SERVICIO FOR EACH ROW WHEN (NEW.IDSERVICIO IS NULL) BEGIN :NEW.IDSERVICIO := SQ_SERVICIO.NEXTVAL;
END;
/

CREATE TABLE CLIENTE
  (
    IDCLIENTE NUMBER NOT NULL ,
    CIUDAD    VARCHAR2 (30 CHAR) ,
    PAIS      VARCHAR2 (20 CHAR) ,
    IDUSU     NUMBER NOT NULL
  ) ;
CREATE UNIQUE INDEX PK_CLIENTE ON CLIENTE
  (
    IDCLIENTE ASC
  )
  ;
  ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY ( IDCLIENTE ) ;
CREATE SEQUENCE SQ_CLIENTE START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TG_CLIENTE BEFORE
  INSERT ON CLIENTE FOR EACH ROW WHEN (NEW.IDCLIENTE IS NULL) BEGIN :NEW.IDCLIENTE := SQ_CLIENTE.NEXTVAL;
END;
/

CREATE TABLE EMPLEADO
  (
    IDEMPLEADO    NUMBER NOT NULL ,
    PUESTOLABORAL VARCHAR2 (30 CHAR) ,
    FECHAINGRESO  DATE DEFAULT SYSDATE ,
    FECHASALIDA   DATE ,
    FECHACREACION DATE DEFAULT SYSDATE ,
    IDUSU         NUMBER NOT NULL
  ) ;
CREATE UNIQUE INDEX PK_EMPLEADO ON EMPLEADO
  (
    IDEMPLEADO ASC
  )
  ;
  ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY ( IDEMPLEADO ) ;
CREATE SEQUENCE SQ_EMPLEADO START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TG_EMPLEADO BEFORE
  INSERT ON EMPLEADO FOR EACH ROW WHEN (NEW.IDEMPLEADO IS NULL) BEGIN :NEW.IDEMPLEADO := SQ_EMPLEADO.NEXTVAL;
END;
/

CREATE TABLE HABITACION
  (
    IDHABITACION  NUMBER NOT NULL ,
    NROHABITACION VARCHAR2 (5 CHAR) NOT NULL ,
    DISPONIBLE    VARCHAR2 (1 CHAR) DEFAULT '1' ,
    DESCRIPCION   VARCHAR2 (100 CHAR) ,
    IDTIPOHAB     NUMBER NOT NULL
  ) ;
CREATE UNIQUE INDEX PK_HABITACION ON HABITACION
  (
    IDHABITACION ASC
  )
  ;
  ALTER TABLE HABITACION ADD CONSTRAINT PK_HABITACION PRIMARY KEY ( IDHABITACION ) ;
  ALTER TABLE HABITACION ADD CONSTRAINT HABITACION_UN UNIQUE ( NROHABITACION ) ;
CREATE SEQUENCE SQ_HABITACION START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TG_HABITACION BEFORE
  INSERT ON HABITACION FOR EACH ROW WHEN (NEW.IDHABITACION IS NULL) BEGIN :NEW.IDHABITACION := SQ_HABITACION.NEXTVAL;
END;
/

CREATE TABLE RESERVA
  (
    IDRESERVA        NUMBER NOT NULL ,
    HABITACIONES     NUMBER ,
    FECHALLEGADA     DATE ,
    FECHASALIDA      DATE ,
    ESTADO           VARCHAR2 (12 CHAR) DEFAULT 'EN CURSO' ,
    FECHACANCELACION DATE ,
    FECHACREACION    DATE DEFAULT SYSDATE ,
    IDCLIENTE        NUMBER NOT NULL ,
    IMPORTEESTIMADO  NUMBER ,
    COMENTARIOS      VARCHAR2 (1000 CHAR) ,
    IDEMPLEADO       NUMBER
  ) ;
CREATE UNIQUE INDEX PK_RESERVA ON RESERVA
  (
    IDRESERVA ASC
  )
  ;
  ALTER TABLE RESERVA ADD CONSTRAINT PK_RESERVA PRIMARY KEY ( IDRESERVA ) ;
CREATE SEQUENCE SQ_RESERVA START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TG_RESERVA BEFORE
  INSERT ON RESERVA FOR EACH ROW WHEN (NEW.IDRESERVA IS NULL) BEGIN :NEW.IDRESERVA := SQ_RESERVA.NEXTVAL;
END;
/

CREATE TABLE DETALLE_RESERVA_HABITACION
  (
    IDRESERVA    NUMBER NOT NULL ,
    IDHABITACION NUMBER NOT NULL
  ) ;
CREATE UNIQUE INDEX PK_RESERVA_HABITACION ON DETALLE_RESERVA_HABITACION
  (
    IDRESERVA ASC , IDHABITACION ASC
  )
  ;
  ALTER TABLE DETALLE_RESERVA_HABITACION ADD CONSTRAINT PK_RESERVA_HABITACION PRIMARY KEY ( IDHABITACION , IDRESERVA ) ;

CREATE TABLE DETALLE_RESERVA_SERVICIO
  (
    IDRESERVA  NUMBER NOT NULL ,
    IDSERVICIO NUMBER NOT NULL
  ) ;
CREATE UNIQUE INDEX PK_RESERVA_SERVICIO ON DETALLE_RESERVA_SERVICIO
  (
    IDRESERVA ASC , IDSERVICIO ASC
  )
  ;
  ALTER TABLE DETALLE_RESERVA_SERVICIO ADD CONSTRAINT PK_RESERVA_SERVICIO PRIMARY KEY ( IDRESERVA , IDSERVICIO ) ;


ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_USUARIO_FK FOREIGN KEY ( IDUSU ) REFERENCES USUARIO ( IDUSU ) ON
DELETE CASCADE NOT DEFERRABLE ;

ALTER TABLE DETALLE_RESERVA_HABITACION ADD CONSTRAINT FK_RESERVA_HABITACION FOREIGN KEY ( IDRESERVA ) REFERENCES RESERVA ( IDRESERVA ) ON
DELETE CASCADE NOT DEFERRABLE ;

ALTER TABLE DETALLE_RESERVA_HABITACION ADD CONSTRAINT FK_HABITACION_RESERVA FOREIGN KEY ( IDHABITACION ) REFERENCES HABITACION ( IDHABITACION ) ON
DELETE CASCADE NOT DEFERRABLE ;

ALTER TABLE DETALLE_RESERVA_SERVICIO ADD CONSTRAINT FK_RESERVA_SERVICIO FOREIGN KEY ( IDRESERVA ) REFERENCES RESERVA ( IDRESERVA ) ON
DELETE CASCADE NOT DEFERRABLE ;

ALTER TABLE DETALLE_RESERVA_SERVICIO ADD CONSTRAINT FK_SERVICIO_RESERVA FOREIGN KEY ( IDSERVICIO ) REFERENCES SERVICIO ( IDSERVICIO ) ON
DELETE CASCADE NOT DEFERRABLE ;

ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_USUARIO_FK FOREIGN KEY ( IDUSU ) REFERENCES USUARIO ( IDUSU ) ON
DELETE CASCADE NOT DEFERRABLE ;

ALTER TABLE HABITACION ADD CONSTRAINT FK_HABITACION_TIPO FOREIGN KEY ( IDTIPOHAB ) REFERENCES TIPOHABITACION ( IDTIPOHAB ) ON
DELETE CASCADE NOT DEFERRABLE ;

ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_CLIENTE_FK FOREIGN KEY ( IDCLIENTE ) REFERENCES CLIENTE ( IDCLIENTE ) ON
DELETE CASCADE NOT DEFERRABLE ;

COMMIT;

-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             9
-- CREATE VIEW                              0
-- ALTER TABLE                             21
-- ALTER INDEX                              0
-- DROP TABLE                               0
-- DROP INDEX                               0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE SEQUENCE                          7
-- ALTER SEQUENCE                           0
-- DROP SEQUENCE                            0
-- CREATE MATERIALIZED VIEW                 0
-- DROP VIEW                                0

-- 
-- ERRORS                                   0
-- WARNINGS                                 0
