/**   INSERTS TO USUARIO  **/
INSERT INTO USUARIO(USUARIO, PASSWORD, NOMBRE, APELLIDOPAT, APELLIDOMAT, EMAIL, TIPO)
VALUES('GUSTAVO.RAMOS','e919c49d5f0cd737285367810a3394d0','GUSTAVO','RAMOS','MONTALVO','GUSTAVO@PRUEBA.COM', 'CLIENTE');

INSERT INTO USUARIO(USUARIO, PASSWORD, NOMBRE, APELLIDOPAT, APELLIDOMAT, EMAIL, TIPO)
VALUES('ALDO.MUSTIGA','e919c49d5f0cd737285367810a3394d0','ALDO','MUSTIGA','COLLAO','ALDO@PRUEBA.COM', 'CLIENTE');

INSERT INTO USUARIO(USUARIO, PASSWORD, NOMBRE, APELLIDOPAT, APELLIDOMAT, EMAIL, TIPO)
VALUES('CHRISTIAN.LAZO','e919c49d5f0cd737285367810a3394d0','CHRISTIAN','LAZO','ROBLES','CHRISTIAN@PRUEBA.COM', 'EMPLEADO');

INSERT INTO USUARIO(USUARIO, PASSWORD, NOMBRE, APELLIDOPAT, APELLIDOMAT, EMAIL, TIPO)
VALUES('BEATRIZ.TICSE','e919c49d5f0cd737285367810a3394d0','BEATRIZ','TICSE','CUEVA','BEATRIZ@PRUEBA.COM', 'CLIENTE');

INSERT INTO USUARIO(USUARIO, PASSWORD, NOMBRE, APELLIDOPAT, APELLIDOMAT, EMAIL, TIPO)
VALUES('NATALIA.MALAGA','e919c49d5f0cd737285367810a3394d0','NATALIA','MALAGA','SANTOS','NATALIA@PRUEBA.COM', 'EMPLEADO');

INSERT INTO USUARIO(USUARIO, PASSWORD, NOMBRE, APELLIDOPAT, APELLIDOMAT, EMAIL, TIPO)
VALUES('DANIEL.OCHOA','e919c49d5f0cd737285367810a3394d0','DANIEL','OCHOA','CRUZ','DANIEL@PRUEBA.COM', 'CLIENTE');

----------------------------------------------------------------------------------------------------------------------------------------

/**   INSERTS TO CLIENTE  **/
INSERT INTO CLIENTE(CIUDAD,PAIS,IDUSU)
VALUES('LIMA','PERU',(SELECT IDUSU FROM USUARIO WHERE USUARIO = 'GUSTAVO.RAMOS'));

INSERT INTO CLIENTE(CIUDAD,PAIS,IDUSU)
VALUES('LIMA','PERU',(SELECT IDUSU FROM USUARIO WHERE USUARIO = 'ALDO.MUSTIGA'));

INSERT INTO CLIENTE(CIUDAD,PAIS,IDUSU)
VALUES('LIMA','PERU',(SELECT IDUSU FROM USUARIO WHERE USUARIO = 'BEATRIZ.TICSE'));

INSERT INTO CLIENTE(CIUDAD,PAIS,IDUSU)
VALUES('BOGOTA','COLOMBIA',(SELECT IDUSU FROM USUARIO WHERE USUARIO = 'DANIEL.OCHOA'));

----------------------------------------------------------------------------------------------------------------------------------------

/**   INSERTS TO EMPLEADO  **/
INSERT INTO EMPLEADO(PUESTOLABORAL, IDUSU)
VALUES('PERSONAL DE MANTENIMIENTO',(SELECT IDUSU FROM USUARIO WHERE USUARIO = 'CHRISTIAN.LAZO'));

INSERT INTO EMPLEADO(PUESTOLABORAL, IDUSU)
VALUES('BOTON',(SELECT IDUSU FROM USUARIO WHERE USUARIO = 'NATALIA.MALAGA'));

----------------------------------------------------------------------------------------------------------------------------------------

/**   INSERTS TO TIPOHABITACION  **/
INSERT INTO TIPOHABITACION(NOMBRE, PRECIO)
VALUES('INDIVIDUAL', 30.00);

INSERT INTO TIPOHABITACION(NOMBRE, PRECIO)
VALUES('DOBLE', 55.00);

INSERT INTO TIPOHABITACION(NOMBRE, PRECIO)
VALUES('MATRIMONIAL', 90.00);

INSERT INTO TIPOHABITACION(NOMBRE, PRECIO)
VALUES('TRIPLE', 115.00);

INSERT INTO TIPOHABITACION(NOMBRE, PRECIO)
VALUES('JUNIOR SUITE', 120.00);

INSERT INTO TIPOHABITACION(NOMBRE, PRECIO)
VALUES('SUITE', 150.00);

----------------------------------------------------------------------------------------------------------------------------------------

/**   INSERTS TO SERVICIOS  **/
INSERT INTO SERVICIO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('DESAYUNO', 'DESAYUNO DE CALIDAD, VARIEDAD Y REPOSICIÓN', 20.00);

INSERT INTO SERVICIO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('ESTACIONAMIENTO', 'ESPACIO PROPIO TEMPORAL PARA VEHICULOS DE TRANSPORTE', 30.00);

INSERT INTO SERVICIO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('SERVICIO DE INTERNET', 'SERVICIO DE INTERNET INALÁMBRICO', 20.00);

INSERT INTO SERVICIO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('ALMUERZO', 'ALMUERZO DE CALIDAD, VARIEDAD Y REPOSICIÓN', 30.00);

INSERT INTO SERVICIO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('CENA', 'CENA DE CALIDAD, VARIEDAD Y REPOSICIÓN', 18.00);

INSERT INTO SERVICIO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('PISCINA', 'ACCESO A LA PISCINA DEL HOTEL', 18.00);

INSERT INTO SERVICIO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('SPA', 'SPA PARA MASAJES Y TRATAMIENTOS REGENERATIVOS', 40.00);

INSERT INTO SERVICIO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('GIMNASIO', 'GIMNASIO EXCLUSIVO PARA CLIENTES', 50.00);

INSERT INTO SERVICIO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('LAVANDERIA', 'LAVANDERIA', 20.00);

----------------------------------------------------------------------------------------------------------------------------------------

/**   INSERTS TO HABITACION  **/
INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('101', 'HABITACION DE PRIMERO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('103', 'HABITACION DE PRIMERO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('105', 'HABITACION DE PRIMERO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'DOBLE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('107', 'HABITACION DE PRIMERO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'MATRIMONIAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('109', 'HABITACION DE PRIMERO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'TRIPLE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('202', 'HABITACION DE SEGUNDO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'MATRIMONIAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('204', 'HABITACION DE SEGUNDO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'DOBLE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('206', 'HABITACION DE SEGUNDO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('208', 'HABITACION DE SEGUNDO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'JUNIOR SUITE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('210', 'HABITACION DE SEGUNDO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('301', 'HABITACION DE TERCER PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('303', 'HABITACION DE TERCER PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'DOBLE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('305', 'HABITACION DE TERCER PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('307', 'HABITACION DE TERCER PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'MATRIMONIAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('309', 'HABITACION DE TERCER PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'SUITE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('402', 'HABITACION DE CUARTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'SUITE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('404', 'HABITACION DE CUARTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'JUNIOR SUITE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('406', 'HABITACION DE CUARTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('408', 'HABITACION DE CUARTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'DOBLE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('410', 'HABITACION DE CUARTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('501', 'HABITACION DE QUINTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('503', 'HABITACION DE QUINTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'DOBLE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('505', 'HABITACION DE QUINTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('507', 'HABITACION DE QUINTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'SUITE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('509', 'HABITACION DE QUINTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'TRIPLE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('602', 'HABITACION DE SEXTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('604', 'HABITACION DE SEXTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'TRIPLE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('606', 'HABITACION DE SEXTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'MATRIMONIAL'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('608', 'HABITACION DE SEXTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'JUNIOR SUITE'));

INSERT INTO HABITACION(NROHABITACION, DESCRIPCION, IDTIPOHAB)
VALUES('610', 'HABITACION DE SEXTO PISO', (SELECT IDTIPOHAB FROM TIPOHABITACION WHERE NOMBRE = 'INDIVIDUAL'));

----------------------------------------------------------------------------------------------------------------------------------------

/**   INSERTS TO RESERVA  **/
INSERT INTO RESERVA(HABITACIONES, FECHALLEGADA, FECHASALIDA, IDCLIENTE, IMPORTEESTIMADO)
VALUES(2, '02/11/2016 17:00', '03/11/2016 8:00', (SELECT A.IDCLIENTE FROM CLIENTE A
                                                  INNER JOIN USUARIO B ON A.IDUSU = B.IDUSU 
                                                  WHERE B.USUARIO = 'GUSTAVO.RAMOS'),
      200.00);

INSERT INTO RESERVA(HABITACIONES, FECHALLEGADA, FECHASALIDA, IDCLIENTE, IMPORTEESTIMADO)
VALUES(1, '02/11/2016 12:00', '02/11/2016 23:00', (SELECT A.IDCLIENTE FROM CLIENTE A
                                                  INNER JOIN USUARIO B ON A.IDUSU = B.IDUSU 
                                                  WHERE B.USUARIO = 'ALDO.MUSTIGA'),
      150.00);
      
INSERT INTO RESERVA(HABITACIONES, FECHALLEGADA, FECHASALIDA, IDCLIENTE, IMPORTEESTIMADO)
VALUES(2, '01/11/2016 23:00', '02/11/2016 6:00', (SELECT A.IDCLIENTE FROM CLIENTE A
                                                  INNER JOIN USUARIO B ON A.IDUSU = B.IDUSU 
                                                  WHERE B.USUARIO = 'BEATRIZ.TICSE'),
      220.00);

----------------------------------------------------------------------------------------------------------------------------------------

/**   INSERTS TO RESERVA HABITACION  **/
INSERT INTO DETALLE_RESERVA_HABITACION(IDRESERVA, IDHABITACION)
VALUES((SELECT A.IDRESERVA FROM RESERVA A
        INNER JOIN CLIENTE B ON A.IDCLIENTE = B.IDCLIENTE
        INNER JOIN USUARIO C ON B.IDUSU = C.IDUSU
        WHERE C.USUARIO = 'GUSTAVO.RAMOS'),
        (SELECT A.IDHABITACION FROM HABITACION A
        INNER JOIN TIPOHABITACION B ON A.IDTIPOHAB = B.IDTIPOHAB
        WHERE B.NOMBRE = 'INDIVIDUAL' AND A.NROHABITACION = 101));
        
INSERT INTO DETALLE_RESERVA_HABITACION(IDRESERVA, IDHABITACION)
VALUES((SELECT A.IDRESERVA FROM RESERVA A
        INNER JOIN CLIENTE B ON A.IDCLIENTE = B.IDCLIENTE
        INNER JOIN USUARIO C ON B.IDUSU = C.IDUSU
        WHERE C.USUARIO = 'GUSTAVO.RAMOS'),
        (SELECT A.IDHABITACION FROM HABITACION A
        INNER JOIN TIPOHABITACION B ON A.IDTIPOHAB = B.IDTIPOHAB
        WHERE B.NOMBRE = 'INDIVIDUAL' AND A.NROHABITACION = 101));

INSERT INTO DETALLE_RESERVA_HABITACION(IDRESERVA, IDHABITACION)
VALUES((SELECT A.IDRESERVA FROM RESERVA A
        INNER JOIN CLIENTE B ON A.IDCLIENTE = B.IDCLIENTE
        INNER JOIN USUARIO C ON B.IDUSU = C.IDUSU
        WHERE C.USUARIO = 'GUSTAVO.RAMOS'),
        (SELECT A.IDHABITACION FROM HABITACION A
        INNER JOIN TIPOHABITACION B ON A.IDTIPOHAB = B.IDTIPOHAB
        WHERE B.NOMBRE = 'INDIVIDUAL' AND A.NROHABITACION = 103));

INSERT INTO DETALLE_RESERVA_HABITACION(IDRESERVA, IDHABITACION)
VALUES((SELECT A.IDRESERVA FROM RESERVA A
        INNER JOIN CLIENTE B ON A.IDCLIENTE = B.IDCLIENTE
        INNER JOIN USUARIO C ON B.IDUSU = C.IDUSU
        WHERE C.USUARIO = 'BEATRIZ.TICSE'),
        (SELECT A.IDHABITACION FROM HABITACION A
        INNER JOIN TIPOHABITACION B ON A.IDTIPOHAB = B.IDTIPOHAB
        WHERE B.NOMBRE = 'DOBLE' AND A.NROHABITACION = 105));
        
INSERT INTO DETALLE_RESERVA_HABITACION(IDRESERVA, IDHABITACION)
VALUES((SELECT A.IDRESERVA FROM RESERVA A
        INNER JOIN CLIENTE B ON A.IDCLIENTE = B.IDCLIENTE
        INNER JOIN USUARIO C ON B.IDUSU = C.IDUSU
        WHERE C.USUARIO = 'BEATRIZ.TICSE'),
        (SELECT A.IDHABITACION FROM HABITACION A
        INNER JOIN TIPOHABITACION B ON A.IDTIPOHAB = B.IDTIPOHAB
        WHERE B.NOMBRE = 'DOBLE' AND A.NROHABITACION = 204));
        
INSERT INTO DETALLE_RESERVA_HABITACION(IDRESERVA, IDHABITACION)
VALUES((SELECT A.IDRESERVA FROM RESERVA A
        INNER JOIN CLIENTE B ON A.IDCLIENTE = B.IDCLIENTE
        INNER JOIN USUARIO C ON B.IDUSU = C.IDUSU
        WHERE C.USUARIO = 'ALDO.MUSTIGA'),
        (SELECT A.IDHABITACION FROM HABITACION A
        INNER JOIN TIPOHABITACION B ON A.IDTIPOHAB = B.IDTIPOHAB
        WHERE B.NOMBRE = 'INDIVIDUAL' AND A.NROHABITACION = 206));

-----------------------------------------------------------------------------------------------------------------------------
COMMIT;

SELECT * FROM DETALLE_RESERVA_HABITACION;
SELECT * FROM RESERVA;
SELECT * FROM TIPOHABITACION;
SELECT * FROM HABITACION;
SELECT * FROM SERVICIO;
SELECT * FROM TIPOHABITACION;
SELECT * FROM EMPLEADO;
SELECT * FROM EMPLEADO;
SELECT * FROM CLIENTE;
SELECT * FROM USUARIO;